server:
  port: 8080
  servlet:
    context-path: /
    encoding:      charset: utf-8
      enabled: true

spring:  datasource:    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cgv?serverTimezone=Asia/Seoul
    username: cgv
    password: cgv1234
  jpa:    open-in-view: true
    hibernate:      ddl-auto: update
      naming:        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    show-sql: true
    properties:      hibernate.format_sql: true
  
  jackson:    serialization:      fail-on-empty-beans: false
      
  servlet:    multipart:      enabled: true  batch:    job:      enabled: false
file:
  path: C:\Users\SAMSUNG\OneDrive\바탕 화면\CGV-Web-App-Project\cgvserver\src\main\resources\upload